# Generated by Django 5.2.4 on 2025-08-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='group',
        ),
        migrations.AddField(
            model_name='category',
            name='store_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('ecommerce', 'E-commerce')], default='grocery', max_length=20),
        ),
    ]
