# Generated by Django 5.2.4 on 2025-08-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_group_category_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store_type',
        ),
        migrations.AddField(
            model_name='category',
            name='segment',
            field=models.CharField(choices=[('grocery', 'Grocery / بقالة'), ('ecom', 'E-commerce / متجر إلكتروني')], default='grocery', max_length=20),
        ),
    ]
