# Generated by Django 5.2.4 on 2025-08-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_product_reorder_level'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='suppliers.supplier'),
        ),
    ]
